# Generated by Django 2.1.7 on 2019-02-25 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_added_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='added_by',
            new_name='organizer',
        ),
    ]
