# Generated by Django 2.1.7 on 2019-02-26 09:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_auto_20190225_1454'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookedEvent',
            new_name='Booking',
        ),
    ]
