# Generated by Django 2.1.7 on 2019-02-26 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20190226_0959'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['release_date', 'title']},
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_tickets',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='events.Event'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.ImageField(upload_to='event_posters'),
        ),
    ]
